### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by stastnypremysl** [Patryk27/lxd-snapper#2]
Hello.

I can't build your project. Here is the build output:

```
p-dev@velvet ~/lxd-snapper $ cargo build
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.45
   Compiling serde_derive v1.0.117
   Compiling libc v0.2.79
   Compiling autocfg v1.0.1
   Compiling serde v1.0.117
   Compiling version_check v0.9.2
   Compiling byteorder v1.3.4
   Compiling memchr v2.3.3
   Compiling ryu v1.0.5
   Compiling lazy_static v1.4.0
   Compiling anyhow v1.0.33
   Compiling itoa v0.4.6
   Compiling unicode-width v0.1.8
   Compiling bitflags v1.2.1
   Compiling unicode-segmentation v1.6.0
   Compiling serde_json v1.0.59
   Compiling hashbrown v0.9.1
   Compiling linked-hash-map v0.5.3
   Compiling termcolor v1.1.0
   Compiling dtoa v0.4.6
   Compiling strsim v0.10.0
   Compiling encode_unicode v0.3.6
   Compiling os_str_bytes v2.3.2
   Compiling vec_map v0.8.2
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling indexmap v1.6.0
   Compiling yaml-rust v0.4.4
   Compiling heck v0.3.1
   Compiling csv-core v0.1.10
   Compiling regex-automata v0.1.9
   Compiling quote v1.0.7
   Compiling atty v0.2.14
   Compiling time v0.1.44
   Compiling dirs v1.0.5
   Compiling pathsearch v0.2.0
   Compiling colored v1.9.3
   Compiling term v0.5.2
   Compiling thiserror-impl v1.0.21
   Compiling clap_derive v3.0.0-beta.2
   Compiling thiserror v1.0.21
   Compiling bstr v0.2.13
   Compiling chrono v0.4.19
   Compiling serde_yaml v0.8.13
   Compiling clap v3.0.0-beta.2
   Compiling csv v1.1.3
   Compiling lib_lxd v0.0.0 (/home/p/p-dev/lxd-snapper/libs/lxd)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> libs/lxd/src/lib.rs:3:1
  |
3 | #![feature(try_blocks)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `lib_lxd`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I am using cargo and rustc version 1.47.0.

Thanks for your help.

P.

**Comment by Patryk27** [comment]
Hi, `lxd-snapper` requires nightly Rust to be compiled - as soon as you do e.g. `rustup default nightly`, it should all work out.

If this nightly-requirement proves to be somewhat troublesome for you, please let me know and we'll figure something out :-)

**Comment by stastnypremysl** [comment]
Hello.

The nightly-requirement is terrible for me in the moment, because I can't make an ebuild to Gentoo repo and I had to place the binaries directly into servers (It's really weird feeling, when you use Gentoo 😄 ).

I hope, that the try catch thing in your code will be soon in the stable version of Rust and then I can do the things in the normal way.

**Comment by Patryk27** [comment]
I've checked and getting `lxd-snapper` to compile on the stable compiler should be pretty easy - I'll try to send appropriate patches tomorrow 😄

**Comment by Patryk27** [comment]
@stastnypremysl fyi, I've just released v1.1 (tagged `v1.1`) that compiles on stable rustc 1.49+.

**Comment by Patryk27** [comment]
If you don't mind, I'm just gonna close this issue to keep the list clean - if you have some compiling issues, feel free to re-open it :-)
